### ISSUE TITLE
Power gatherer misses ticks when doing 3t4g

### ISSUE THREAD

**Issue by Bee-Ar** [Ganom/Supporter-Issue-Tracker#163]
**Describe the bug**
While doing 3t4g, the power gatherer will randomly miss ticks and break out of a 3t cycle, dropping efficiency by 30-40%. Happens after a clean install of the plugins.

**To Reproduce**
Start power gatherer with the proper 3t4g settings at granite

**Expected behavior**
Should not miss ticks

**Screenshots**
[example of behavior here](https://streamable.com/11flef)

**Additional context**
some logs that correlate to when I'm running the plugin
```2021-01-20 12:32:51 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
2021-01-20 12:35:17 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
2021-01-20 12:35:24 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
2021-01-20 12:35:26 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
2021-01-20 12:38:01 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 2
2021-01-20 12:38:02 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 2
2021-01-20 12:38:44 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 3
2021-01-20 12:38:47 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:38:48 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:38:50 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:38:51 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:39:17 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:39:19 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:39:21 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:39:23 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:39:24 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 0
2021-01-20 12:41:59 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
2021-01-20 12:41:59 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
2021-01-20 12:42:07 [Client] INFO  net.runelite.client.plugins.ec - Cant find a cached object? Cache Size: 1
```

I consistently get this issue - I only have ganom's plugins installed. From my experience the only way I can fix this is to completely nuke my installation and remove all plugins, uninstall oprs, then clean all the files and subdirectories at `%USER%\.runelite\externalmanager` before reinstalling.

Other things that I have tried that don't work:
- leaving plugin on but not active-> clearing marked objects -> resetting config 
- make plugin inactive-> disabler plugin through oprs plugin configs -> clearing marked objects -> resetting config 

one thing to note is that it works perfectly fine if the item's to drop setting is completely empty - it doesn't miss any ticks, but obviously it doesn't work well since it doesn't drop items.

**Comment by Bee-Ar** [comment]
Other notes:
- behavior is reproducible even on low ping (<30 ping) worlds - it doesn't improve with lower ping
- i've nuked my local installation more than 3 times to get this to work
- on win10, oprs stable build

**Comment by Ganom** [comment]
I'd need to see the full logs, but that log line typically indicates an object marked but not in the scene.
I've pushed a change that might fix it, let me know.

**Comment by Bee-Ar** [comment]
Whatever you did  slightly fixed it - missing less cycles now. I can give you full logs if you'd like, but there's not much else there. See attached
[client.log](https://github.com/Ganom/Supporter-Issue-Tracker/files/5853689/client.log)

**Comment by Ganom** [comment]
> Whatever you did slightly fixed it - missing less cycles now. I can give you full logs if you'd like, but there's not much else there. See attached
> [client.log](https://github.com/Ganom/Supporter-Issue-Tracker/files/5853689/client.log)

In those logs, you have an uncaught exception causing you're client thread to die. Not sure why it was having issues trying to connect to the oprs session service.

```
Caused by: java.net.UnknownHostException: No such host is known (session.openosrs.dev)
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
```
