### ISSUE TITLE
RCBot: Plugin disappears.

### ISSUE THREAD

**Issue by DaSernet** [Ganom/Supporter-Issue-Tracker#28]
**Describe the bug**
The RC bot plugin disappears from the list, it stays in your folder and the hotkey keeps recognizing being pressed.

**To Reproduce**
1. Go to RC BOt
2. Click on Mind
3. Start script (I had only teleport tabs to the altar and dueling ring equipped)
4. Start/stop script a few times, try to get it to work. (it won't since the setup is incorrect)
5. Restart client
6. Boom the RC Bot has disappeared. 
7. The rc bot stays active, the button to active it still recognises being pressed, which makes other scripts not work.

Reproduced on my laptop + main PC.

**Comment by DaSernet** [comment]
2020-07-11 12:16:48 [scheduled-0] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 58540 locally stored loot records
2020-07-11 12:17:20 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: null
	at net.runelite.client.plugins.externals.rcbot.Runecrafter.a(Runecrafter.java:15)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:179)
	at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:144)
	at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:115)
	at net.runelite.client.callback.Hooks.post(Hooks.java:175)
	at client.onAddChatMessage(Client.java:1512)
	at an.o(WorldMapID.java:32)
	at cn.m(ObjectSound.java:19)
	at client.gt(Client.java:6240)
	at client.ft(Client.java:2617)
	at client.ab(Client.java:907)
	at bn.e(GameShell.java:358)
	at bn.run(GameShell.java:337)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Ganom** [comment]
Fixed in release 1.0.5
